Repository hmcts/ccd-case-activity-api, pull requests merged in 2019-06, with the labels that each got.

#148 Cleaned up Helm chart implementation
  Jenkinsfile_CNP
  app/redis/redis-client.js
  charts/ccd-case-activity-api/Chart.yaml
  charts/ccd-case-activity-api/requirements.yaml
  charts/ccd-case-activity-api/values.aat.template.yaml
  charts/ccd-case-activity-api/values.template.yaml
Labels: ns:ccd-case-activity-api-pr-148

#149 added test exclusion
  sonar-project.properties
Labels: ns:ccd-case-activity-api-pr-149

#150 moved sonar conf to config file
  package.json
  sonar-project.properties
Labels: ns:ccd-case-activity-api-pr-150
