Repository hmcts/ccd-case-activity-api, pull requests merged in 2020-10, with the labels that each got.

#233 Removing Health checks scenario as smoke tests
  aat/src/resources/features/F-000/F-000.feature
  aat/src/resources/features/F-018/F-018.feature
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-233

#235 Rdm 9551 tf onto develop
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-235

#236 Removed redundant dependency audit - pipeline has it already
  Jenkinsfile_CNP
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-236
