Repository hmcts/ccd-case-activity-api, pull requests merged in 2020-05, with the labels that each got.

#195 BEFTA PATCH: temporarily turn header checks to warning mode
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-activity-api-pr-195

#194 RDM-7650 use JSON Def file functionality in befta
  aat/build.gradle
Labels: ns:ccd, rel:ccd-case-activity-api-pr-194

#193 RDM-8393 Update nodejs-healthcheck to 1.6.0
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-case-activity-api-pr-193

#196 RDM-8304 Caching of /o/userprofile calls
  .gitignore
  app/cache/cache-config.js
  app/cache/cache-service.js
  app/user/auth-checker-user-only-filter.js
  app/user/cached-user-resolver.js
  app/user/user-request-authorizer.js
  app/user/user-resolver.js
  app/util/jwt.js
  charts/ccd-case-activity-api/Chart.yaml
  charts/ccd-case-activity-api/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  package.json
  test/e2e/getActivities-end-to-end-test.spec.js
  test/e2e/store-cleanup-end-to-end-test.spec.js
  test/e2e/utils/delayed.js
  test/spec/app/cache/cache-service.spec.js
  test/spec/app/route/get-activities.spec.js
  test/spec/app/user/auth-checker-user-only-filter.spec.js
  test/spec/app/user/cached-user-resolver.spec.js
  test/spec/app/user/user-request-authorizer.spec.js
  test/spec/app/user/white-black-list-roles-authorizer.spec.js
  test/spec/app/util/jwt.spec.js
  yarn.lock
Labels: ns:ccd, rel:ccd-case-activity-api-pr-196

#197 Update Jenkinsfile_CNP rm installCharts
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-activity-api-pr-197
