Repository hmcts/ccd-case-activity-api, pull requests merged in 2020-04, with the labels that each got.

#189 Rdm 7440
  README.md
  aat/build.gradle
  aat/src/resources/features/F-000/S-000.td.json
Labels: ns:ccd, rel:ccd-case-activity-api-pr-189

#181 RDM-7843-Stale-PR
  .github/stale.yml
Labels: ns:ccd, rel:ccd-case-activity-api-pr-181

#176 RDM-7632 - Replacing /details with /o/userinfo
  app/routes/add-activity.js
  app/service/activity-service.js
  app/user/user-resolver.js
  charts/ccd-case-activity-api/Chart.yaml
  charts/ccd-case-activity-api/requirements.yaml
  config/default.yaml
  test/e2e/addActivity-end-to-end-test.spec.js
  test/e2e/getActivities-end-to-end-test.spec.js
  test/e2e/utils/test-utils.js
  test/spec/app/route/add-activity.spec.js
  test/spec/app/service/activity-service.spec.js
Labels: ns:ccd, rel:ccd-case-activity-api-pr-176
