Repository hmcts/ccd-case-activity-api, pull requests merged in 2020-02, with the labels that each got.

#167 RDM-3593 - Update to node 12.x
  .travis.yml
  Dockerfile
  infrastructure/main.tf
  package.json
Labels: ns:ccd, rel:ccd-case-activity-api-pr-167

#169 RDM-3593 - Update to node 12.x - MASTER
  .travis.yml
  Dockerfile
  infrastructure/main.tf
  package.json
Labels: ns:ccd, rel:ccd-case-activity-api-pr-169

#165 RDM-7434 Introduce BEFTA FW into repository
  .gitignore
  .project
  Jenkinsfile_CNP
  README.md
  aat/.gitignore
  aat/build.gradle
  aat/gradle/wrapper/gradle-wrapper.jar
  aat/gradle/wrapper/gradle-wrapper.properties
  aat/gradlew
  aat/gradlew.bat
  aat/settings.gradle
  aat/src/aat/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityBeftaMain.java
  aat/src/aat/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java
  aat/src/aat/resources/features/F-000/F-000.feature
  aat/src/aat/resources/features/F-000/S-000.td.json
  package.json
Labels: ns:ccd, rel:ccd-case-activity-api-pr-165

#168 RDM-7554 Remove the deprecated enableDockerBuild
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-activity-api-pr-168

#170 Case activity api to prod/base image alpine
  Dockerfile
Labels: ns:ccd, rel:ccd-case-activity-api-pr-170

#172 RDM-2508-Rm-nsp
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-case-activity-api-pr-172
