Repository hmcts/ccd-case-activity-api, pull requests merged in 2021-07, with the labels that each got.

#285 enable HighLevelDataSetup for nightly pipeline
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-285

#287 CCD-1580: Integrate Fortify Scan into Nightly Pipelines
  .gitignore
  Jenkinsfile_nightly
  aat/build.gradle
  aat/config/fortify-client.properties
  aat/gradle/wrapper/gradle-wrapper.properties
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-287

#288 fix for Fortify Issue 14643918 - Dockerfile Misconfiguration: Default User Privilege
  Dockerfile
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-288
