Repository hmcts/ccd-case-activity-api, pull requests merged in 2021-12, with the labels that each got.

#302 CCD-2312: Temporarily disable Fortify Scan in nightly build
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-302

#303 CCD-2344 temporary Ignore failed tests
  aat/src/resources/features/F-018/F-018.feature
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-303

#304 CCD-2344 upgrade nodejs engine library to resolve build issues
  .travis.yml
  Dockerfile
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-304
