Repository hmcts/ccd-case-activity-api, pull requests merged in 2021-06, with the labels that each got.

#275 CCD-1055 Fix Advisory - 1674 in Case Activity API
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-275

#277 CCD-1055 Fix Advisory - 1674 in Case Activity API
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-277

#280 implement high level data setup for automated definition imports
  .gitignore
  Jenkinsfile_CNP
  aat/build.gradle
  aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java
  aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/HighLevelDataSetupApp.java
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-280

#281 tolerate data setup failures and narrow recent import interval
  aat/build.gradle
  aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java
  aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/HighLevelDataSetupApp.java
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-281

#282 Changed Jenkins library reference back to master branch
  Jenkinsfile_CNP
  aat/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-282

#284 befta-fw update to 8.2.0
  Jenkinsfile_CNP
  aat/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-284
