Repository hmcts/ccd-case-activity-api, pull requests merged in 2022-04, with the labels that each got.

#326 --Fix the nightly build
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-326

#329 yarn-audit-know-issues updated due to dependency failure
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-329

#330 yarn-audit-know-issues updated due to dependency failure
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-330

#321 Update ajv to 6.12.3
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-321

#328 CCD-2974: CVE-2022-24785 fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-328
