Repository hmcts/ccd-case-activity-api, pull requests merged in 2022-12, with the labels that each got.

#361 CCD-4088 CVE-2022-24999 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-361

#366 CCD-4017 Upgrade base charts for Jenkins enhancements - bumped nodejs…
  charts/ccd-case-activity-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-366

#358 CCD-4050: Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-358

#368 CCD-4134 CVE-2022-46175 Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-368
