Repository hmcts/ccd-case-activity-api, pull requests merged in 2022-07, with the labels that each got.

#340 CCD-3461: Added Suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-340

#322 CCD-2496 multi arch image update
  Dockerfile
  Jenkinsfile_CNP
  acb.tpl.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-322

#343 CCD-3461: Updated Suppression CVE-2022-31129 ccd-case-activity-api
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-343

#342 CCD-3461: CVE-2022-31129 (ccd-case-activity-api)
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-342

#345 CCD-3561 Upgrade Java and Node JS versions in chart for all the respe…
  charts/ccd-case-activity-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-345
