Repository hmcts/ccd-case-activity-api, pull requests merged in 2022-09, with the labels that each got.

#352 CCD-3569 Fix docker build failures in Node JS repos after multi arch …
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-352

#350 CCD-3647: Fix preview deploy issues
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-350

#346 CCD-3539 : Stop running Nightly builds on weekends
  Jenkinsfile_nightly
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-346
