Repository hmcts/ccd-case-activity-api, pull requests merged in 2022-01, with the labels that each got.

#301 CCD-2293: Update hmcts/properties-volume dependency version
  package.json
  yarn.lock
Labels: stale, ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-301

#306 CCD-2378: Re-enable Fortify scan
  Jenkinsfile_nightly
  aat/build.gradle
  aat/config/fortify-client.properties
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-306

#311 CVE-2022-0235
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-311

#308 Update to build.gradle
  aat/build.gradle
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-308
