Repository hmcts/ccd-case-activity-api, pull requests merged in 2023-01, with the labels that each got.

#371 CCD-4134 CVE-2022-46175 Redo Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-371

#373 CCD-4134 CVE-2022-46175 Redo Suppression 2nd Time
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-373

#369 CCD-4134 CVE-2022-46175 json 5 v2.2.2 resolution added, yarn install …
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-369

#357 CCD-4025 dependabot minimatch ReDoS vulnerability - resolution minima…
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-357

#367 CCD-4097: Auto-suppress CVEs - Node JS apps
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-367

#375 CCD-4173: Auto-suppress CVEs do not allow empty commit
  .github/workflows/auto-suppress-CVEs.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-375

#370 CCD-3796 Update Node Version - upgraded to 16.15.0
  .nvmrc
  .travis.yml
  Dockerfile
  acb.tpl.yaml
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-370

#378 CCD-4218 Fix Jenkins pipeline warnings
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-378
