Repository hmcts/ccd-case-activity-api, pull requests merged in 2023-10, with the labels that each got.

#404 CCD-4845: renovate.json
  .github/renovate.json
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-404

#406 Change resolution of debug@npm
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-406

#401 CCD-4827 upgrade to NodeJS 18.17.0
  .nvmrc
  .travis.yml
  Dockerfile
  aat/build.gradle
  acb.tpl.yaml
  app/user/user-resolver.js
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-401
