Repository hmcts/ccd-case-activity-api, pull requests merged in 2023-02, with the labels that each got.

#380 CCD-4237 CVE-2022-25901 Resolution added cookiejar ^2.1.4, yarn insta…
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-380

#384 CCD-4267
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-384

#382 CCD-4224 Yarn v3 upgrade
  .gitignore
  .travis.yml
  .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
  .yarn/releases/yarn-3.4.1.cjs
  .yarnrc.yml
  Dockerfile
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-382

#383 CCD-4317 Upgrade base charts
  charts/ccd-case-activity-api/Chart.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-383

#385 CCD-4337 : updated package versions
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-385
