Repository hmcts/ccd-case-activity-api, pull requests merged in 2024-09, with the labels that each got.

#428 CCD-5861 : CVE-2024-45296 : Suppressions added
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-428

#429 CCD-5861 : CVE-2024-45296 : updated suppressions
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-429

#436 CVE_reDO
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-436
