Repository hmcts/ccd-case-activity-api, pull requests merged in 2024-11, with the labels that each got.

#442 CCD-5861 : Fix CVE-2024-45296
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-442

#443 CME-45 update to java 21
  .nvmrc
  .travis.yml
  Dockerfile
  aat/build.gradle
  aat/gradle/wrapper/gradle-wrapper.jar
  aat/gradle/wrapper/gradle-wrapper.properties
  aat/gradlew.bat
  acb.tpl.yaml
  charts/ccd-case-activity-api/Chart.yaml
  package.json
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-443

#445 CCD-5968 Fix ccd-case-activity-api Appinsights
  app/app-insights/app-insights.js
  config/default.yaml
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-445

#448 CCD-5968 Downgrade ccd-case-activity-api Appinsights again
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-448
