Repository hmcts/ccd-case-activity-api, pull requests merged in 2024-03, with the labels that each got.

#390 Ccd 4412 deprecated internal urls
  Jenkinsfile_CNP
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-390

#413 CVE-2024-29041 Yarn Report Temp Suppression
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-413

#414 Suppression for CVE
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-414
