Repository hmcts/ccd-case-activity-api, pull requests merged in 2024-07, with the labels that each got.

#419 Befta-fw 9.0.2, ccd-test-definitions 7.22.2, gradle 8.7
  Dockerfile
  aat/build.gradle
  aat/gradle/wrapper/gradle-wrapper.jar
  aat/gradle/wrapper/gradle-wrapper.properties
  aat/gradlew
  aat/src/java/uk/gov/hmcts/ccd/caseactivity/befta/CaseActivityTestAutomationAdapter.java
  app/app-insights/app-insights.js
  charts/ccd-case-activity-api/Chart.yaml
  charts/ccd-case-activity-api/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/test.yaml
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-419

#422 commit suppression changes
  yarn-audit-known-issues
Labels: ns:ccd, prd:ccd, keep-helm, rel:ccd-case-activity-api-pr-422

#423 CCD-5319 : Fix-CVE-2024-29041 / rebuild
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-activity-api-pr-423
